@startuml inline_umlgraph_1.png
[*] -right-> FINISHED : create
FINISHED -right-> READY : start
READY --> RUNNING : dispatch
RUNNING --> READY : preempted
RUNNING -right-> WAITING : wait
WAITING --> READY : release from waiting
RUNNING --> FINISHED : finish
FINISHED --> [*] : destroy
@enduml
